[package]
name = "sjip8"
version = "0.1.0"
authors = ["Oliver Nordbjerg <hi@notbjerg.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.13.0"
rand = "0.7.2"
nfd = "0.0.4"
